version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "user-server"
    hostname: "user-server"
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB=consul
      - DBPORT=8500
    depends_on:
      - consul

  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - ./consul_store:/consul/data
